

server:
  port: 8081

spring:
  application:
    name: devops-dataservice  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
    
feign:
  hystrix:
    enabled: true   # 
management:
  endpoints:
    web:
      exposure:
        include: "*"  # because springboot2.1. must be added, support access /actuator/hystrix.stream
    

    