

server:
  port: 8081

spring:
  application:
    name: devops-dataservice
  cloud:
    service-registry:
      auto-registration:
        enabled: true
        
  security:
    user:
      name: admin
      password: pwd  
    
    
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
   

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
        hibernate:
          format_sql: true
          apply_to_ddl: false
    

  h2:
    console:
      enabled: true
      path: /h2-console
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
    
feign:
  hystrix:
    enabled: true   # 
management:
  endpoints:
    web:
      exposure:
        include: "*"  # because springboot2.1. must be added, support access /actuator/hystrix.stream
    

    